//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDispensaryV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GarageDetail
    {
        public int Id { get; set; }
        public string GarageName { get; set; }
        public string GarageMobile { get; set; }
        public string GarageLocation { get; set; }
        public string License { get; set; }
        public string Password { get; set; }
    }
}
