//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDispensaryV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InteriorImage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InteriorImage()
        {
            this.InventoryDetails = new HashSet<InventoryDetail>();
        }
    
        public int Id { get; set; }
        public string Front { get; set; }
        public string Rear { get; set; }
        public string Boot { get; set; }
        public string Bonet { get; set; }
        public int OId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryDetail> InventoryDetails { get; set; }
    }
}
