//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDispensaryV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryDetail
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public Nullable<int> Mudflaps { get; set; }
        public Nullable<int> WheelCaps { get; set; }
        public Nullable<int> Floormates { get; set; }
        public Nullable<int> Idol { get; set; }
        public Nullable<int> Battery { get; set; }
        public Nullable<int> Documents { get; set; }
        public Nullable<int> FuelMeterRange { get; set; }
        public string OtherRemark { get; set; }
        public Nullable<int> ExId { get; set; }
        public Nullable<int> InId { get; set; }
    
        public virtual ExteriorImage ExteriorImage { get; set; }
        public virtual InteriorImage InteriorImage { get; set; }
    }
}
