//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDispensaryV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public int Id { get; set; }
        public Nullable<int> orderId { get; set; }
        public string part { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<double> amount { get; set; }
    }
}
