//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDispensaryV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrderId { get; set; }
        public string CarRegistrationNo { get; set; }
        public string ManufacturingYear { get; set; }
        public string OdometerReading { get; set; }
        public string VehicleModel { get; set; }
        public string CustomerName { get; set; }
        public string CustMobileNo { get; set; }
        public string CustEmail { get; set; }
        public string CustAddress { get; set; }
        public string VisitMode { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public string GarageName { get; set; }
        public Nullable<double> ServicePrice { get; set; }
        public string VarientName { get; set; }
        public Nullable<bool> ServiceDone { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
